name: Build & Test Package

on: pull_request


jobs:
  build_and_test_package:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Restore
      run: |
        dotnet restore
    - name: Biuld
      run: |
        dotnet build --no-restore
    - name: Test
      run: |
        dotnet restore
  
# github.refname is tag from commit 
